### ISSUE TITLE
mlbgame.day from the future

### ISSUE THREAD

**Issue by FlowFX** [zachpanz88/mlbgame#15]
> /mlbgame/**init**.py l. 173    # do not even try to get data if date is in the future

Why? It works for me if I change the code. But you probably have a reason.

**Comment by zachpanz88** [comment]
Honestly, I did not think that there would be data for the future. Future games may not have certain attributes that completed or in progress games have, but I am not totally sure. I'm going to investigate and update accordingly.

**Comment by FlowFX** [comment]
Looking at http://gd2.mlb.com/components/game/mlb/year_2016/month_08/day_28/scoreboard.xml and http://gd2.mlb.com/components/game/mlb/year_2016/month_08/day_28/gid_2016_08_28_balmlb_nyamlb_1/linescore.xml I don't see a difference between these and those PRE_GAME on the day of the game.

I'd be fine with just getting all games of the upcoming series.

**Comment by zachpanz88** [comment]
I am currently working on allowing dates in the future without breaking the current API.

**Comment by April29th** [comment]
Any progress on getting it to work with future dates? I'm very interested in being able to have it at least catch the pitching matchups & game start times. In another month or so, I'm going to have a bit of free time & am thinking of helping out with the whole project. I've had a similar project I started but had to put aside and now I'm thinking it would be better to work with this instead of duplicating a lot of work.

**Comment by zachpanz88** [comment]
Honestly, I haven't really worked on this much over the last month. I will be resuming development of the project and hopefully adding some new features and ci tests.

@April29th, if you are interested in contributing to the library I would love to have help.

**Comment by zachpanz88** [comment]
I have added this functionality in the dev branch. Feel free to clone that and test it out. This functionality will officially be released in the next release (probably 2.3.0) which will be coming out very soon.
